apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: awesome-pizza-support
nameSuffix: -support

images:
  - name: awesome-pizza
    newName: ghcr.io/your-org/awesome-pizza
    newTag: support-latest

patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
