apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - application.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: awesome-pizza
  app.kubernetes.io/part-of: awesome-pizza
